version: "3.7"

services:
  web:
    ports:
      - 3000:3000
    volumes:
      - ./web:/app

  app:
    ports:
      - 8080:8080

  db:
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: